version: 0.0
os: linux
files:
- source: index.html
destination: /var/www/html
hooks:
BeforeInstall:
- location: /var/scripts/install_dependencies.sh
timeout: 300
runas: root
AfterInstall:
- location: /var/scripts/afterinstall.sh
timeout: 300
runas: root

