version: 0.0
os: linux
files:
- source: /var/
destination: /var/www/html/index.html
hooks:
BeforeInstall:
- location: scripts/install_dependencies.sh
timeout: 300
runas: root
AfterInstall:
- location: scripts/afterinstall.sh
timeout: 300
runas: root

