version: 0.0
os: linux
files:
- source: /var/script/
destination: /var/www/
hooks:
BeforeInstall:
- location: scripts/install_dependencies.sh
timeout: 300
runas: root
AfterInstall:
- location: scripts/afterinstall.sh
timeout: 300
runas: root

